GET https://rentalmanagement-9g1a.onrender.com/estates


###

POST https://task-backend-43vh.onrender.com/todo/new
Content-Type: application/json

{
    "text": "Get the milk",
    "text": "Get bread"
}

###
DELETE https://task-backend-43vh.onrender.com/todo/delete/

###

GET https://task-backend-43vh.onrender.com/todo/complete/65205e50763d8b8dc59cc0b8

