GET http://localhost:3000/todos


###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Get the milk"
}

###
DELETE http://localhost:3001/todo/delete/651e68afed8da65871c57105

###

GET http://localhost:3001/todo/complete/651d661cc162829a0c3d96e8

